# Dump the output of this script into `cno-hpack-huffman.h`.
TABLE = [
    (":authority",                   ""             ), (":method",                      "GET"          ),
    (":method",                      "POST"         ), (":path",                        "/"            ),
    (":path",                        "/index.html"  ), (":scheme",                      "http"         ),
    (":scheme",                      "https"        ), (":status",                      "200"          ),
    (":status",                      "204"          ), (":status",                      "206"          ),
    (":status",                      "304"          ), (":status",                      "400"          ),
    (":status",                      "404"          ), (":status",                      "500"          ),
    ("accept-charset",               ""             ), ("accept-encoding",              "gzip, deflate"),
    ("accept-language",              ""             ), ("accept-ranges",                ""             ),
    ("accept",                       ""             ), ("access-control-allow-origin",  ""             ),
    ("age",                          ""             ), ("allow",                        ""             ),
    ("authorization",                ""             ), ("cache-control",                ""             ),
    ("content-disposition",          ""             ), ("content-encoding",             ""             ),
    ("content-language",             ""             ), ("content-length",               ""             ),
    ("content-location",             ""             ), ("content-range",                ""             ),
    ("content-type",                 ""             ), ("cookie",                       ""             ),
    ("date",                         ""             ), ("etag",                         ""             ),
    ("expect",                       ""             ), ("expires",                      ""             ),
    ("from",                         ""             ), ("host",                         ""             ),
    ("if-match",                     ""             ), ("if-modified-since",            ""             ),
    ("if-none-match",                ""             ), ("if-range",                     ""             ),
    ("if-unmodified-since",          ""             ), ("last-modified",                ""             ),
    ("link",                         ""             ), ("location",                     ""             ),
    ("max-forwards",                 ""             ), ("proxy-authenticate",           ""             ),
    ("proxy-authorization",          ""             ), ("range",                        ""             ),
    ("referer",                      ""             ), ("refresh",                      ""             ),
    ("retry-after",                  ""             ), ("server",                       ""             ),
    ("set-cookie",                   ""             ), ("strict-transport-security",    ""             ),
    ("transfer-encoding",            ""             ), ("user-agent",                   ""             ),
    ("vary",                         ""             ), ("via",                          ""             ),
    ("www-authenticate",             ""             ),
]

C_TABLE = ','.join('{{{{"{}",{}}},{{"{}",{}}}}}'.format(k, len(k), v, len(v)) for k, v in TABLE)
C_TSIZE = len(TABLE)

print('''// !!! AUTOGENERATED !!! see cno-hpack.static.h
static const cno_header_t CNO_HPACK_STATIC_TABLE[]    = {{{C_TABLE}}};
static const size_t       CNO_HPACK_STATIC_TABLE_SIZE = {C_TSIZE};
'''.strip('\n').format_map(globals()))
